portfolio/__init__.py
from flask import Flask
from flask_assets import Environment
from whitenoise import WhiteNoise

from portfolio.views import site

# init the app
app = Flask('portfolio')
app.wsgi_app = WhiteNoise(app.wsgi_app, root='static/')

# config
app.config.from_pyfile('config.py')
app.jinja_env.trim_blocks = True
app.jinja_env.lstrip_blocks = True

# assets
assets = Environment(app)
assets.config['LIBSASS_INCLUDES'] = app.config['LIBSASS_INCLUDES']
assets.config['coffeescript_bin'] = app.config['COFFEE_BIN']
assets.load_path = app.config['WEBASSETS_LOAD_PATH']
assets.from_yaml(app.config['ASSETS'])

# load views
app.register_blueprint(site)

@app.cli.command(help='Compress static files.')
def compress():
    import os
    import shutil
    from whitenoise.compress import main
    shutil.rmtree(os.path.join('portfolio', 'static', '.webassets-cache'))
    main(os.path.join('portfolio', 'static'))

portfolio/views.py
from flask import abort, Blueprint, g, make_response, render_template
from portfolio.minify import render_minified
from portfolio.projects import Project
from portfolio.sitemap import Sitemap

site = Blueprint('site', __name__, static_folder='static')
projects = Project()


# home
@site.route('/')
def index():
    return render_minified('home.html', projects=projects.ordered())


# project pages
@site.route('/<key>/')
def portfolio(key):

    # check if project exists
    if not projects.exist(key):
        return abort(404)

    # load project info
    project = projects.get(key)
    g.title = project['title']
    g.cover = project['cover']
    g.tagline = project['tagline']

    return render_minified('{}.html'.format(key),
                           project=project,
                           suggestions=projects.suggestion(key, 6))


# seo and browser
@site.route('/robots.txt')
def robots():
    response = make_response('User-agent: *\nDisallow:')
    response.headers['Content-Type'] = 'text/plain'
    return response


@site.route('/sitemap.xml')
def sitemap():
    info = Sitemap(project_list=projects.order)
    xml = render_template('sitemap.xml', pages=info.pages)
    response = make_response(xml)
    response.headers['Content-Type'] = 'application/xml'
    return response


@site.route('/favicon.ico')
def favicon():
    return site.send_static_file('imgs/favicon/favicon.ico')


# title and seo info auto generator
@site.context_processor
def title():

    # basic values
    name = 'Mabel Lazzarin'
    about = "{}'s Portfolio | UX & Visual Designer".format(name)
    image = 'cover.jpg'

    # load page specific values
    subtitle = g.get('title', None)
    tagline = g.get('tagline', None)
    title = '{} | {}'.format(subtitle, name) if subtitle else name
    description = tagline if tagline else about
    cover = g.get('cover', image)

    # set page class
    page_class = 'home' if name == title else 'project'

    # return values
    return {'name': name,
            'title': title,
            'description': description,
            'cover': cover,
            'page_class': page_class}

portfolio/templates/_base.html
<!doctype html>
<html lang="en">

    <head>
    
        <!-- basic headers -->
        <meta charset="utf-8">
        <meta name=viewport content="width=device-width,initial-scale=1">
        <title>{{ title }}</title>
    
        <!-- seo & socila networks -->
        <meta name="description" content="{{ description }}">
        <meta name="author" content="{{ name }}">
        <meta property="og:site_name" content="{{ name }}">
        <meta property="og:title" content="{{ title }}">
        <meta property="og:type" content="website">
        <meta property="og:url" content="{{ request.url|replace('portfolio.fcgi/', '') }}">
        <meta property="og:image" content="{{ url_for('site.static', filename='imgs/{}'.format(cover), _external=True)|replace('portfolio.fcgi/', '') }}">
        <meta property="og:description" content="{{ description }}">
        <meta property="twitter:card" content="summary">
        <meta property="twitter:url" content="{{ request.url|replace('portfolio.fcgi/', '') }}">
        <meta property="twitter:title" content="{{ title }}">
        <meta property="twitter:description" content="{{ description }}">
        <meta property="twitter:image" content="{{ url_for('site.static', filename='imgs/{}'.format(cover), _external=True)|replace('portfolio.fcgi/', '') }}"> 
        <meta name="google-site-verification" content="NyFnv7IpyrrUjMTOPv_hN5nc6SFGTbKX28YqdVlZqJM">
    
        <!-- favicons -->
        <link rel="apple-touch-icon" sizes="57x57" href="{{ url_for('site.static', filename='imgs/favicon/apple-touch-icon-57x57.png')}}">
        <link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('site.static', filename='imgs/favicon/apple-touch-icon-114x114.png')}}">
        <link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('site.static', filename='imgs/favicon/apple-touch-icon-72x72.png')}}">
        <link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('site.static', filename='imgs/favicon/apple-touch-icon-144x144.png')}}">
        <link rel="apple-touch-icon" sizes="60x60" href="{{ url_for('site.static', filename='imgs/favicon/apple-touch-icon-60x60.png')}}">
        <link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('site.static', filename='imgs/favicon/apple-touch-icon-120x120.png')}}">
        <link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('site.static', filename='imgs/favicon/apple-touch-icon-76x76.png')}}">
        <link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('site.static', filename='imgs/favicon/apple-touch-icon-152x152.png')}}">
        <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('site.static', filename='imgs/favicon/apple-touch-icon-180x180.png')}}">
        <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('site.static', filename='imgs/favicon/favicon-96x96.png')}}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('site.static', filename='imgs/favicon/favicon-16x16.png')}}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('site.static', filename='imgs/favicon/favicon-32x32.png')}}">
        <meta name="msapplication-TileColor" content="#00aba9">
        <meta name="msapplication-TileImage" content="{{ url_for('site.static', filename='imgs/favicon/mstile-144x144.png')}}">
        <meta name="theme-color" content="#ffffff">
    
        <!-- assets -->
        {% assets 'css' %}
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lato:400,300,700,300italic,400italic,700italic">
        <link rel="stylesheet" href="{{ url_for('static', filename='app.css') }}">
        {% endassets %}

    </head>
    
    <body class="{{ page_class }}">

        <div id="page">

            <div id="top">
                <div class="content">
                    <header>
                        <h1>
                            <a href="{{ url_for('site.index') }}#page">
                                <img src="{{ url_for('site.static', filename='imgs/logo.svg') }}" alt="{{ name }}">
                            </a>
                        </h1>
                        <nav class="menu loaded" id="menu">
                            {% include '_menu.html' %}
                        </nav>
                    </header>
                </div><!-- end .content -->
            </div><!-- end .wrapper -->
            
            <main>
                {% macro img(source, text) %}<img src="{{ url_for('site.static', filename='imgs/{}'.format(source)) }}" alt="{{ text }}">{% endmacro %}
                {% block content %}{% endblock %}
            </main>

            <div id="footer">
                <div class="content">
                    <footer>
                        <ul>
                            <li class="email js">
                                <a href="mailto:hello at mabel dot ml"><img src="{{ url_for('site.static', filename='imgs/icon-email.svg') }}" alt="Email"></a>
                            </li>
                            <li class="linkedin">
                                <a href="http://linkedin.com/in/belxlaz"><img src="{{ url_for('site.static', filename='imgs/icon-linkedin.svg') }}" alt="LinkedIn"></a>
                            </li>
                            <li class="behance">
                                <a href="http://behance.com/belxlaz"><img src="{{ url_for('site.static', filename='imgs/icon-behance.svg') }}" alt="Behance"></a>
                            </li>
                            <li class="tumblr">
                                <a href="http://belxlaz.tumblr.com"><img src="{{ url_for('site.static', filename='imgs/icon-tumblr.svg') }}" alt="Tumblr"></a>
                            </li>
                            <li class="twitter">
                                <a href="http://twitter.com/belxlaz"><img src="{{ url_for('site.static', filename='imgs/icon-twitter.svg') }}" alt="Twitter"></a>
                            </li>
                            <li class="instagram">
                                <a href="http://instagram.com/belxlaz"><img src="{{ url_for('site.static', filename='imgs/icon-instagram.svg') }}" alt="Instagram"></a>
                            </li>
                        </ul>
                    </footer>
                </div><!-- end .content -->
            </div><!-- end #footer -->

        </div><!-- end #page -->

        <nav class="menu-mobile loaded">
            {% include '_menu.html' %}
        </nav>

        {% assets 'js' %}
        <script src="{{ url_for('site.static', filename='app.js') }}"></script>
        {% endassets %}

        {% if config['INSERT_GOOGLE_ANALYTICS'] and 'mabel.ml' in request.url %}
        <script>ga('create', '{{ config['GOOGLE_ANALYTICS'] }}', 'auto'); ga('send', 'pageview');</script>
        {% endif %}

    </body>
</html>

portfolio/templates/_menu.html
<ul class="menu-links">
    <li><a href="{{ url_for('site.index') }}#about">About</a></li>
    <li><a href="{{ url_for('site.index') }}#projects">Projects</a></li>
    <li><a href="{{ url_for('site.index') }}#contacts">Contact</a></li>
</ul>

portfolio/templates/_suggestions.html
            {% if suggestions %}
            <div id="suggestions">
                <div class="content">
                    <h5>Other projects</h5>
                    <ul>
                        {% for project in suggestions %}
                        <li>
                            <a href="{{ url_for('site.portfolio', key=project['key']) }}">{{ img(project['cover'], project['title']) }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div><!-- end .content -->
            </div><!-- end li#suggestions -->
            {% endif %}

portfolio/templates/ares.html
    {% extends "_base.html" %}
{% block content %}

                <div id="project-header">
                    <header>
                        <div class="wide vertical-crop">
                            {{ img('projects-ares-cover.jpg', project['title']) }}
                        </div><!-- end .wide -->
                        <div class="info">
                            <div class="content">
                                <h2>
                                    Brastemp Ative!
                                    <span>A global washer & dryer machine project</span>
                                </h2>
                                <dl>
                                    <dt>My role</dt>
                                    <dd>Graphic Design, CFM, UI/UX Design</dd>
                                    <dt>Team</dt>
                                    <dd>Whirlpool - Industrial Design (Global)</dd>
                                    <dt>Awards</dt>
                                    <dd>IF Design</dd>
                                </dl>
                            </div><!-- end .project-content -->
                        </div><!-- end .info -->
                        <div class="summary">
                            <div class="content">
                                <div class="briefing">
                                    <h3>Brief</h3>
                                    <p>This product was a Whirlpool Global project which brought together the Brazilian, Asian and European Design teams. The main challenge was to combine the needs of consumers from different cultures in a single product platform.</p>
                                </div><!-- end .briefing -->
                                <div class="solution">
                                    <h3>Solution</h3>
                                    <p>Designed to be simple and elegant, with outstanding features, it was developed through constant assessments with consumers, such as usability tests, perceived quality and heuristic evaluations. The graphic design, the CFM and the UI behaviour were adapted according to the differences between countries.<p>
                                </div><!-- end .solution-->
                            </div><!-- end .project-content -->
                        </div><!-- end .summary -->
                    </header>
                </div><!-- end #project-header -->
                
                <div id="project-content">
                    <div class="wide">
                        {{ img('projects-ares-interface.jpg', 'Interface') }}
                    </div><!-- end .wide -->
                    <div class="content centered">
                        <article class="no-split">
                            <div class="row">
                                <div class="whole">
                                    <h3>Interface</h3>
                                    <p>A central white backlit knob with surrounding luminescence was embedded to an elegant and slim user interface. The emotional experience is enhanced by fading lights that follow the status of the washing and drying cycles. The dead-front display with touch sensors brings cutting-edge technologies to traditional white goods. The UI was projected to help even inexperienced users in choosing the better settings for their clothes.</p>
                                </div>
                            </div>
                        </article>
                    </div>                
                    <div class="wide">
                        {{ img('projects-ares-colours.jpg', 'Colours') }}
                    </div>         
                    <div class="content ares-cfm">
                        <div class="third">
                            <h3>Colours, Finishes and Materials</h3>
                            <p>In terms of colours, Brastemp Ative! offers 3 CMF options which easily blend into any home environment: Global White, Satin Chrome and All Black.</p>
                        </div>
                    </div>
                    <div class="wide ares-top">
                        {{ img('projects-ares-top.jpg', 'Top view') }}
                    </div>
                    <div class="wide">
                        {{ img('projects-ares-test.jpg', 'Usability test') }}
                    </div>
                </div><!-- end #project-content -->
                {% include '_suggestions.html' %}
{% endblock %}

portfolio/templates/clubsoda.html
{% extends "_base.html" %}
{% block content %}

                <div id="project-header">
                    <header>
                        <div class="wide vertical-crop">
                            {{ img('projects-clubsoda-cover.jpg', project['title']) }}
                        </div><!-- end .wide -->
                        <div class="info">
                            <div class="content">
                                <h2>
                                    Club Soda
                                    <span>Social network to reduce or stop drinking</span>
                                </h2>
                                <dl>
                                    <dt>My role</dt>
                                    <dd>UX Design, Graphic Design</dd>
                                    <dt>Team partners</dt>
                                    <dd>Christine Phan, Philippe Campagne, Luis Klefsjo</dd>
                                    <dt>Duration</dt>
                                    <dd>2.5 weeks</dd>
                                </dl>
                            </div><!-- end .project-content -->
                        </div><!-- end .info -->
                        <div class="summary">
                            <div class="content">
                                <div class="briefing">
                                    <h3>Brief</h3>
                                    <p>Club Soda is an online support group for people who want to change their relationship with alcohol.  Our final project of the UX Design course at General Assembly was to design an “expert and perks marketplace” for their current website, including a searchable database that enables members to find experts related to their goals. Currently, experts are listed on the website with a photo, a very short description, and an external link to the expert’s website.</p>
                                </div><!-- end .briefing -->
                                <div class="solution">
                                    <h3>Solution</h3>
                                    <p>We decided to expand upon the initial briefing and created elements to increase members’ and experts’ engagement – a social media approach where a delightful community and professional support goes hand in hand. Our deliverable consisted of a welcoming landing page for both experts and members, and a special type of account enabling experts to sign up and create their own profiles. As a result, experts are encouraged to upload and edit their own content (events, texts, videos).</p>
                                </div><!-- end .solution-->
                            </div><!-- end .project-content -->
                        </div><!-- end .summary -->
                    </header>
                </div><!-- end #project-header -->
                
                <div id="project-content">
                    <div class="wide">
                        <p>{{ img('projects-clubsoda-team.jpg', 'Team') }}</p>
                    </div><!-- end .wide -->
                    <div class="content">
                        <article>
                            <div class="row">
                                <div class="third">
                                    <div class="wide">
                                        {{ img('projects-clubsoda-competitors.jpg', 'Competitive Analysis') }}
                                    </div>
                                    <h4>Competitive Analysis</h4>
                                    <p>Many existing websites and apps that offer support to people wishing to stop drinking have a gloomy, clinical, and guilt-bearing approach. We broadened our research to cover social websites, which inspired us to encourage people to interact online.</p>
                                </div>
                                <div class="third">
                                    <div class="wide">
                                        {{ img('projects-clubsoda-research.jpg', 'User Research') }}
                                    </div>
                                    <h4>User Research</h4>
                                    <p>To help us understand the Club Soda target, first we created an online survey asking what people are looking for in a community when they decided on a big change in their lives. Next we conducted in-depth interviews with existing participants of the Club Soda community: 6 members; and 5 experts.</p>
                                </div>
                                <div class="third">
                                    <div class="wide">
                                        {{ img('projects-clubsoda-personas.jpg', 'Personas') }}
                                    </div>
                                    <h4>Personas</h4>
                                    <p>Analysing the data from the survey and interviews, we identified some patterns and created personas to make tangible our findings. Julia represents the members’ side and Angelo the experts’. Their needs, pain points, and habits drove our decisions.</p>
                                </div>
                            </div><!-- end .row -->
                            <div class="row">
                                <div class="third">
                                    <div class="wide">
                                        {{ img('projects-clubsoda-userjorney.jpg', 'User Journey') }}
                                    </div>
                                    <h4>User Journey</h4>
                                    <p class="pre-split">We mapped out Club Soda's current opportunities for interaction for members and experts in their first access to the site. The lower points are the worst experiences during their journeys. These graphics became our guideline for feature improvements.</p>
                                </div>
                                <div class="third">
                                    <div class="wide">
                                        {{ img('projects-clubsoda-studio.jpg', 'Design Studio') }}
                                    </div>
                                    <h4>Design Studio</h4>
                                    <p class="pre-split">In a workshop with the Club Soda founder, developers, members, and enthusiasts, we started the feature prioritization and drew the first sketches in a method where everybody participates in the design process.</p>
                                </div>
                                <div class="third">
                                    <div class="wide">
                                        {{ img('projects-clubsoda-testing.jpg', 'User testing') }}
                                    </div>
                                    <h4>User testing</h4>
                                    <p class="pre-split">From paper to high fidelity digital prototyping, 13 users tested our design, in 5 rounds of iterations based upon their feedback. After further iterations we proceeded to our deliverable prototype.</p>
                                </div>
                            </div><!-- end .row -->
                        </article>
                        <article class="no-split">
                            <h3>Outcomes</h3>
                            <p class="pre-split">As a start up company in an accelerator programme, Club Soda is using our prototypes to raise investment. The feedback from founders, experts, and members were very positive and Club Soda wish to implement the solution as soon as possible. If you would like to access the complete project, please click <a href="http://goo.gl/3CitGl">here</a>.</p>
                            <div class="half">
                                <h4>Registration</h4>
                                <p class="pre-split">To create an enjoyable experience from the beginning, we redesigned the signup process with fewer steps by integrating the experts’ registration, and setting keywords for interests, hobbies and other topics they would like more information on.</p>
                            </div>
                            <div class="half">
                                <h4>Experts and Perks</h4>
                                <p class="pre-split">List of available Experts and Perks with basic information on display. Showing possible Premium Member discounts. Upon clicking, the user will be taken to their specific profile page.</p>
                            </div>
                        </article>
                    </div><!-- end .content -->
                    <div class="wide">
                        {{ img('projects-clubsoda-deliver2.jpg', 'Regitration') }}
                    </div>
                    <div class="content">
                        <article class="no-split">
                            <div class="half">
                                <h4>Landing Page</h4>
                                <p class="pre-split">A complete new layout was suggested to centralize meaningful contents for each user. On the top of the page, an image carousel shows featured Club Soda campaigns.Then a display with appointments, goal and achievements creates a gamification approach, showing rewards for being part of the community. This page shows events, other members’ events, experts and contents related with the keywords you set.</p>
                            </div>
                            <div class="half">
                                <h4>Expert Page</h4>
                                <p class="pre-split">A set of new features was included to empower experts to participate actively in Club Soda’s community. The profile page gathers his description, testimonials, events, links and all the content he already created inside the platform.  He is able to edit this information anytime he wants; he can even upload videos, articles and create events.</p>
                            </div>
                        </article>
                        </div><!-- end .content -->
                    <div class="wide">
                        {{ img('projects-clubsoda-deliver1.jpg', 'Deliver') }}
                    </div>     
                </div><!-- end #project-content -->

                {% include '_suggestions.html' %}

{% endblock %}

portfolio/templates/home.html
{% extends "_base.html" %}
{% block content %}

                <div id="about">
                    <div class="wide vertical-crop">
                        <img src="{{ url_for('site.static', filename='imgs/cover.jpg') }}" alt="{{ name }}"> 
                    </div><!-- end .wide -->
                    <div class="content">
                        <article>
                            <h2>Hi, I'm Mabel Lazzarin</h2>
                            <p>I'm a designer who is passionate about creating products, services and interactive experiences through a human-centred approach. I previously worked in interdisciplinary and international teams at <a href="http://www.whirlpool.com.br/">Whirlpool</a> and <a href="http://www.intelbras.com.br/">Intelbras</a>, designing a variety of projects, such as home appliances, telephones, electronic security products and softwares. </p>
                            <p>I just completed the <a href="http://generalassemb.ly/education/user-experience-design-immersive">UX Design</a> immersive course at <a href="http://generalassemb.ly/">General Assembly</a> which offered me fresh ideas on best practices for the creative industry. Now I’m looking forward to finding an opportunity in London to combine my background skills and my new learnings to create intuitive and delightful user experiences.</p>
                        </article><!-- end #about -->
                    </div><!-- end .content -->
                    <div class="work-interests">
                        <div class="content">
                            <div>
                                <h2>Work Interests</h2>
                                <ul>
                                    <li>
                                        {{ img('icon-ux.svg', 'Experience design') }}
                                        Experience<br>design
                                    </li>
                                    <li>
                                        {{ img('icon-graphic.svg', 'Graphic design') }}
                                        Graphic<br>design
                                    </li>
                                    <li>
                                        {{ img('icon-trend.svg', 'Trend research') }}
                                        Trend<br>research
                                    </li>
                                </ul>
                            </div>
                        </div><!-- end .content -->
                    </div><!-- end .work-interests -->
                </div><!-- end #about -->

                <div id="projects">
                    <div class=content>
                        <article>
                            <h2>Projects</h2>
                            <ul class="filter">
                                <li class="active" data-keywords="ux, graphic, trend">All</li>
                                <li data-keywords="ux">Experience<br>Design</li>
                                <li data-keywords="graphic">Graphic<br>Design</li>
                                <li data-keywords="trend">Trend<br>Research</li>
                            </ul>
                            <ul class="gallery">
                                {% for project in projects %}
                                <li class="{{ project['keywords']|join(' ') }}">
                                    <a href="{{ url_for('site.portfolio', key=project['key']) }}">
                                        <img alt="{{ project['title'] }}" src="{{ url_for('site.static', filename='imgs/{}'.format(project['cover'])) }}">
                                        <div class="description">
                                            <h5>{{ project['title'] }}</h5>
                                            <h6>{{ project['tagline'] }}</h6>
                                        </div><!-- end .description -->
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </article>
                    </div><!-- end .content -->
                </div><!-- end #projects -->

                <div id="contacts">
                    <div class="content">
                        <article class="no-split">
                            <h2>Contact</h2>
                            <p>If you are interested to know more about my work or just want to talk about design in general, I'll be happy to hear from you. Feel free to get in touch:</p>
                        </article>
                    </div><!-- end .content -->
                </div><!-- end #contacts -->

{% endblock %}